{{- $image := .Values.image -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onboarding-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: onboarding-operator
    app.kubernetes.io/name: onboarding-operator
    {{- include "onboarding.labels" . | nindent 4 }}
{{- with $image.pullSecrets }}
imagePullSecrets:
{{ toYaml . }}
{{- end }}
