{{- $component := .Values.gateway -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{ $component.name }}
    istio.io/rev: default
    app.kubernetes.io/name: {{ $component.name }}
    {{- include "onboarding.labels" . | nindent 4 }}
  name: {{ $component.name }}-sds
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $component.name }}-sds
subjects:
- kind: ServiceAccount
  name: {{ $component.name }}-service-account
