{{- $component := .Values.gateway -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ $component.name }}
    istio.io/rev: default
    app.kubernetes.io/name: {{ $component.name }}
    {{- include "onboarding.labels" . | nindent 4 }}
  name: {{ $component.name }}-sds
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
