{{- $image := .Values.image -}}
{{- $component := .Values.gateway -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ $component.name }}
    istio: ingressgateway
    istio.io/rev: default
    app.kubernetes.io/name: {{ $component.name }}
    {{- include "onboarding.labels" . | nindent 4 }}
  name: {{ $component.name }}-service-account
  namespace: {{ .Release.Namespace }}
{{- with $image.pullSecrets }}
imagePullSecrets:
{{ toYaml . }}
{{- end }}
