secrets:
  clusterServiceAccount:
    clusterFQN: ""
    encodedJWK: ""
  cveScannerServiceAccount:
    token: ""
spec:
  components:
    cveScanner:
      enabled: true
      schedule: "@midnight"
      service:
        address: "tis.tetrate.io:443/api"
        addressScheme: "https"
    serviceDiscoverer:
      enabled: true
      schedule: "@every 10s"
    configValidator:
      enabled: true
      schedule: "@midnight"
      istioNamespace: "istio-system"
  centralPlane:
    host: "central"
    port: 9080
    plaintext: true
    caCert: ""
image:
  registry: addon-containers.istio.tetratelabs.com
  name: agent
  tag: 1.0.0-rc6
  pullPolicy: IfNotPresent
  pullSecrets: []
serviceAccount:
  # Set this flag to "true" to create a service account.
  create: true
  # Set the name of the service account to use.
  name: ""
  # Example of how to associate AWS IAM role with ServiceAccount for AWS Cloud Map integration
  # https://docs.aws.amazon.com/eks/latest/userguide/associate-service-account-role.html
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::819220072900:role/cloudmap-read
  annotations: {}

---