apiVersion: v1
kind: ServiceAccount
metadata:
  name: tis-central-plane
  namespace: {{ .Release.Namespace }}
  labels:
    app: tis-central-plane

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tis-central-plane
  labels:
    app: tis-central-plane
    platform.tis.tetrate.io/application: tis-central-plane
    platform.tis.tetrate.io/component: central
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tis-central-plane
subjects:
  - kind: ServiceAccount
    name: tis-central-plane
    namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tis-central-plane
  labels:
    app: tis-central-plane
    platform.tis.tetrate.io/application: tis-central-plane
    platform.tis.tetrate.io/component: central
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update"]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get" ]
