apiVersion: v1
kind: Secret
metadata:
  labels:
    app: tis-central-plane
  name: tis-admin-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{.Values.user.admin.username}}: {{.Values.user.admin.password | sha256sum | b64enc}}

---

{{- if .Values.user.ldap.enable -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: tis-central-plane
  name: tis-ldap-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  binddn: "{{ .Values.user.ldap.credentials.binddn | b64enc }}"
  bindpassword: "{{ .Values.user.ldap.credentials.bindpassword | b64enc }}"
{{ end }}

---

{{- if .Values.service.cve.token }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: tis-central-plane
  name: tis-cve-token
type: Opaque
data:
  token: "{{ .Values.service.cve.token | b64enc }}"
{{ end }}