apiVersion: v1
kind: Service
metadata:
  name: tis-central-plane-lb
  namespace: {{ .Release.Namespace }}
  labels:
    app: tis-central-plane
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: tis-central-plane

---

apiVersion: v1
kind: Service
metadata:
  name: tis-central-plane
  namespace: {{ .Release.Namespace }}
  labels:
    app: tis-central-plane
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: tis-central-plane