apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
data:
  ISTIO_REGISTRY_SYNC_ENABLE: "{{ .Values.istioRegistrySync.enable }}"
  ISTIO_REGISTRY_SYNC_RESYNC_PERIOD: "{{ .Values.istioRegistrySync.resyncPeriod }}"
  ISTIO_REGISTRY_SYNC_PUBLISH_NAMESPACE: "{{ .Values.istioRegistrySync.publishNamespace }}"
  ISTIO_REGISTRY_SYNC_CONSUL_ENDPOINT: "{{ .Values.istioRegistrySync.consul.endpoint }}"
  ISTIO_REGISTRY_SYNC_CLOUD_MAP_REGION: "{{ .Values.istioRegistrySync.cloudMap.region }}"
