apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - networking.istio.io
    resources:
      - serviceentries
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "agent.fullname" . }}
    namespace: {{ .Release.Namespace }}
