apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLUSTER_SERVICE_ACCOUNT_CLUSTER_FQN: {{ .Values.secrets.clusterServiceAccount.clusterFQN }}
  CLUSTER_SERVICE_ACCOUNT_ENCODED_JWK: {{ .Values.secrets.clusterServiceAccount.encodedJWK }}
  CVE_SCANNER_SERVICE_ACCOUNT_TOKEN: {{ .Values.secrets.cveScannerServiceAccount.token }}
  CENTRAL_PLANE_CA_CERT: {{ .Values.spec.centralPlane.caCert | quote }}
