apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "agent.selectorLabels" . | nindent 6 }}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
