# Image configuration for the onboarding images.
image:
  # Image repository from where download the onboarding images.
  repository:  addon-containers.istio.tetratelabs.com
  # Onboarding image tag to be used.
  tag:  0.1.0-onboarding
  # Image pull policy to be used to pull the onboarding images.
  pullPolicy: IfNotPresent
  # Image pull secrets to be used to pull the onboarding images.
  pullSecrets: []

istio:
  revisions: []

onboarding:
  endpoint:
    # Hostname of the onboarding endpoint.
    host: onboarding-endpoint.example
    # TLS secret name to be used for the onboarding endpoint.
    # This secret should be created in the same namespace where the onboarding operator is deployed.
    tlsSecretName: onboarding-endpoint-tls-cert

operator:
  logLevel: "all:info"
  kubeSpec:
    deployment:
      replicaCount: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 128Mi

repository:
  onboardingPackageIstioSidecar:
    # Sidecar version to be used in the onboarding package. This should be the same as the installed TID version.
    tag: 1.24.3-tetrate3
  kubeSpec:
    deployment:
      replicaCount: 1
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 32Mi

gateway:
  # Name of the gateway. This name will be used for the gateway service and the gateway deployment.
  name: vmgateway
  # The network that the gateway belongs to. The VMGateway is a east-west gateway and must know about the kubernetes network to route traffic.
  network: "kube-network"
  kubeSpec:
    service:
      annotations: {}
    deployment:
      replicaCount: 1
      resources:
        limits:
          cpu: "1"
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 2Gi
