apiVersion: v1
kind: Service
metadata:
  name: onboarding-repository
  namespace: {{.Release.Namespace}}
  labels:
    app: onboarding-repository
    app.kubernetes.io/name: onboarding-repository
    {{- include "onboarding.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: onboarding-repository
