apiVersion: v1
name: istio-default
# This version is never actually shipped. istio/release-builder will replace it at build-time
# with the appropriate version
version: 1.20.3+tetrate2
appVersion: 1.20.3-tetrate2
description: Helm chart for istio default revision components.
keywords:
  - istio
sources:
  - https://github.com/istio/istio
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
