image:
  registry: addon-containers.istio.tetratelabs.com
  name: central
  tag: 1.0.0
  pullPolicy: IfNotPresent
  pullSecrets: []
user:
  admin:
    username: admin
    password: admin
  jwt:
    expiration: 3600s
  ldap:
    # please update the enable status and the configuration below to enable LDAP
    enable: false
#    config:
#      host: ldap
#      port: 389
#      disableTLS: true
#      search:
#        baseDN: dc=tetrate,dc=io
#        recursive: true
#        pagesize: 20000000
#      iam:
#        matchDN: "cn=%s,ou=People,dc=tetrate,dc=io"
#        matchFilter: "(&(objectClass=person)(uid=%s))"
#      sync:
#        usersFilter: "(objectClass=person)"
#        groupsFilter: "(objectClass=groupOfUniqueNames)"
#        membershipAttribute: uniqueMember
#    credentials:
#      binddn: test
#      bindpassword: test

persistent:
  enable: true
  keyPrefix: central-storage-
  valueSize: 512
  flushInterval: 10s
service:
  tls:
    enable: false
    useGeneratedCerts: true # Toggle between using generated certs and pre-existing TLS secret
    secretName: "" # Name of the pre-existing Kubernetes TLS secret
    generated: # Generated cert options, here user need to specify CA cert and key
      cert: ""
      key: ""
      extraDnsNames: []
      #  - "central.tis.com"
  http:
    port: 8080
    deploymentPath: ""
  grpc:
    port: 9080
  cve:
    keepDays: 30
    cron: "@midnight"
    token: ""
  config_validation:
    keepDays: 30
    cron: "@midnight"
  cluster_status_detector:
    cron: "@every 1m"
    lost_connection_duration: "2m"

---