image:
  registry: addon-containers.istio.tetratelabs.com
  name: central
  tag: 1.0.0-test1
  pullPolicy: IfNotPresent
  pullSecrets: []
user:
  admin:
    username: admin
    password: admin
  jwt:
    expiration: 3600s
  ldap:
    # please update the enable status and the configuration below to enable LDAP
    enable: false
#    config:
#      host: ldap
#      port: 389
#      disableTLS: true
#      search:
#        baseDN: dc=tetrate,dc=io
#        recursive: true
#        pagesize: 20000000
#      iam:
#        matchDN: "cn=%s,ou=People,dc=tetrate,dc=io"
#        matchFilter: "(&(objectClass=person)(uid=%s))"
#      sync:
#        usersFilter: "(objectClass=person)"
#        groupsFilter: "(objectClass=groupOfUniqueNames)"
#        membershipAttribute: uniqueMember
#    credentials:
#      binddn: test
#      bindpassword: test

persistent:
  enable: true
  keyPrefix: central-storage-
  valueSize: 1024
  flushInterval: 10s
service:
  http:
    port: 8080
    deploymentPath: ""
  grpc:
    port: 9080
  cve:
    keepDays: 30
    cron: "@midnight"
    token: ""
ingress:
  # Please update the enable status and the configuration below to enable Ingress
  enabled: false
  #  className: ""
  #  annotations: {}
  #  hosts:
  #    - host: central.tis.com
  #      paths:
  #        - path: /
  #          pathType: ImplementationSpecific
  #  tls: []
  ##    - secretName: chart-example-tls
  ##      hosts:
  ##        - chart-example.local

---