apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "istio-registry-sync.fullname" . }}-cluster-role
  labels:
  {{- include "istio-registry-sync.selectorLabels" . | nindent 4 }}
rules:
- apiGroups: ["networking.istio.io"]
  resources: ["serviceentries"]
  verbs: ["create", "get", "list", "watch", "patch", "delete", "update"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create"]
- apiGroups: ["multicluster.x-k8s.io"]
  resources: ["serviceimports"]
  verbs: ["create", "get", "list", "watch", "patch", "delete", "update"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: [ "create", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "istio-registry-sync.fullname" . }}-rolebinding
  labels:
  {{- include "istio-registry-sync.selectorLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "istio-registry-sync.fullname" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "istio-registry-sync.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
